### ISSUE TITLE
XCode 7 is not supported

### ISSUE THREAD

**Issue by kgadzinowski** [jonreid/XcodeCoverage#40] opened 2015-09-22 12:29 UTC
When running on XCode 7 I get:

lcov: ERROR: no valid records found in tracefile Coverage.info
Reading data file Coverage.info
genhtml: ERROR: no valid records found in tracefile Coverage.info
Coverage report is in lcov folder

**Comment by jonreid** [comment] 2015-09-23 01:14
Xcode 7 generates coverage in a different file format.
More info in this article: https://www.bignerdranch.com/blog/weve-got-you-covered/
I'm keeping an eye on this: https://github.com/venmo/slather/issues/89

**Comment by DaidoujiChen** [comment] 2015-09-24 08:02
the same issue.

**Comment by mmesutt** [comment] 2015-10-21 08:28
the same issue.

**Comment by perfectpapa** [comment] 2015-11-13 07:33
the same issue

**Comment by jonreid** [comment] 2015-11-13 16:11
How are things with the lcov update, as of 77afcfc?

**Comment by michaelmyers** [comment] 2015-11-14 20:42
Jon,

Pulling from master, it looks like it is almost back.  I had to make the lcov scripts executable and then added `get_version.sh` from lcov to suppress the error created by [this line](https://github.com/jonreid/XcodeCoverage/blob/master/lcov-1.12/bin/lcov#L75).  

It looks like the `Line Data` count is off (the numbers are gigantic, `58411*10^7`, maybe an unsigned vs signed int issue) however the bigger issue I am experiencing is the `cannot merge previous GCDA file: corrupt arc tag` console spam followed by a crash.  It generates some of the gcda files so the `getcov` script will process the ones available but (I believe) that crash is preventing the majority of the gcda files from being created.

The consensus after a couple of searches on how to solve the `cannot merge` issue is to turn off instrumentation and code coverage support, which doesn't help us out.  I will report back if I figure anything else out.

Also, thanks for your hard work on the project.  You are fighting the good fight. 
 
Michael

**Comment by bixbarton** [comment] 2015-11-23 17:45
Hi Michael - where did you get get_version.sh from? 

Also, I'm getting problems. I generate env.sh from within XCode, seemingly ok, then call getcov which starts a scan for GCDA files from the root /. Weird.

**Comment by michaelmyers** [comment] 2015-11-23 17:57
@bixbarton You can get `get_version.sh` from the [lcov project](http://ltp.sourceforge.net/coverage/lcov.php), the development version is [here](https://github.com/linux-test-project/lcov/blob/master/bin/get_version.sh) on github.  Xcodecoverage uses lcov to convert the coverage data to HTML.  

I have not seen the root scan issue that you describe.

**Comment by bixbarton** [comment] 2015-11-24 14:48
Thanks Michael, I put that file in place and things run smoother. The root scan issue was my mistake, not setting the environment variables correctly.

Only issue I have now is that Xcode 7 isn't generating any GCDA files for this project. Utterly bizarre. Code Coverage is on, Legacy is on.

**Comment by bixbarton** [comment] 2015-11-25 18:00
Ok, so the reason I'm not generating GCDA files is that INSTRUMENT_PROGRAM_FLOW is set to NO. But setting it to YES causes my test run to fail. Lots of "cannot merge previous GCDA file: corrupt arc tag" entries in the console, and it then crashes in main.m showing BAD_ACCESS on the line calling UIApplicationMain.

I cannot turn INSTRUMENT_PROGRAM_FLOW on for the main target, but without it, I cannot generate GCDA files.

Anyone have any ideas for this?

**Comment by bixbarton** [comment] 2015-12-14 15:06
Is XcodeCoverage going to be updated to work with the LLVM-COV profdata file?

**Comment by jstevenco** [comment] 2015-12-22 00:55
FYI -- I am seeing the same behavior @bixbarton describes with the crash in main.m.  Confirmed on Xcode 7.2.

**Comment by jonreid** [comment] 2015-12-25 19:17
Thanks to everyone for investigating this while I was occupied elsewhere.

I've made the lcov scripts executable, and added the missing script. "Seems to work" so far on a library, but I haven't tried an app yet.

@bixbarton and @jstevenco, could you verify that you have the following enabled:

GCC_GENERATE_TEST_COVERAGE_FILES
CLANG_ENABLE_CODE_COVERAGE
GCC_INSTRUMENT_PROGRAM_FLOW_ARCS

**Comment by bixbarton** [comment] 2015-12-25 19:19
I can verify that Jon. All 3 are set to yes.

**Comment by jonreid** [comment] 2015-12-25 19:29
*sigh* https://forums.developer.apple.com/thread/9765

**Comment by Panajev** [comment] 2016-02-29 14:54
I was able to generate code coverage on our project which uses the iOS 9 SDK, but the lcov version in the current tagged release (which the pod references is wrong): https://github.com/jonreid/XcodeCoverage/issues/43.

**Comment by jonreid** [comment] 2016-03-01 03:34
Closing, at least for now.

**Closed by jonreid** 2016-03-01 03:34 UTC

**Comment by Manoj412** [comment] 2016-06-07 05:46
Still I am getting coverage.info empty...Can some one help me please.
